# Generated by Django 4.2.7 on 2023-12-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Twitter_app", "0003_tweet"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="img/"),
        ),
    ]
